# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  #push:
  #  branches: ['latest']
  #schedule:
  #  - cron: "0 */2 * * *"
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: caddy:latest
          image: ${{ env.IMAGE_NAME }}:latest
          #image: caddy:latest
          
    #  - name: Log in to the Container registry
    #    uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #    with:
    #      registry: ${{ env.REGISTRY }}
    #      username: ${{ github.actor }}
    #      password: ${{ secrets.GITHUB_TOKEN }}
    #    if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      # only execute subsequent steps if an update is actually NEEDED.
      # unfortunately we need to add an if-condition to all steps now
      # because a clean exit can't be triggered within a job it seems
      # (a cancellation is NOT the same and triggers a failure email)
      # see also https://github.com/actions/runner/issues/662

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

    #  - name: Extract metadata (tags, labels) for Docker
    #    id: meta
    #    uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #    with:
    #      images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #    if: steps.baseupdatecheck.outputs.needs-updating == 'true'

    #  - name: Build and push Docker image
    #    uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #    with:
    #      context: .
    #      push: true
    #      tags: ${{ steps.meta.outputs.tags }}
    #      labels: ${{ steps.meta.outputs.labels }}
    #    if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }} # update for your image
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
